### ISSUE TITLE
translate function produces wrong results

### ISSUE THREAD

**Issue by andreas-wilm** [jhbadger/nimbioseq#6]
Hey, either I'm doing something fundamentally wrong or the translate function doesn't work as intended:

- CACCCTTCCCCTCCCGACCGT gets translated into LPAPPIQ (should be HPSPPDR)
- TCCCCTTATCGCCGCGACGAT gets translated into APVHHIM (should be SPYRRDD)

Can issue PR for a fix. Just want to double check that this is indeed wrong.

Best,
Andreas

**Comment by jhbadger** [comment]
Yes, I confirmed that this was a problem due to the order I kept the codons in. I changed the order of the codon to number mapping and the results are now correct. Also, I include support for all the NCBI variant genetic codes besides defaulting to the standard.
